### ISSUE TITLE
赶紧注释掉 watch

### ISSUE THREAD

**Issue by 2AP9** [hyird/Action-Openwrt#2]
赶紧注释掉 workflows/build-openwrt.yml 下面两行，不然谁点击 star 都会开始编译。

#  watch:
#    types: started

**Comment by hyird** [comment]
if: github.event.repository.owner.id == github.event.sender.id
没看见这个么 不会的

**Comment by 2AP9** [comment]
哦，不过看Actions界面的编译队列挺乱的

**Comment by hyird** [comment]
> 哦，不过看Actions界面的编译队列挺乱的

太容易炸了 没办法 一堆红叉叉
