### ISSUE TITLE
源码仓库地址使用自己备份过来的设为私人的仓库是不是不行？

### ISSUE THREAD

**Issue by ldsj007** [hyird/Action-Openwrt#3]
我填了克隆的设为的私人的仓库，到下载源码那一步就报错了。

Run git clone https://github.com/ldsj007/LIENOL-Open-2020-10-10 -b 19.07 openwrt
  git clone https://github.com/ldsj007/LIENOL-Open-2020-10-10 -b 19.07 openwrt
  shell: /bin/bash -e {0}
  env:
    RUN_VALIDATION: true
    DATE: 2020-10-13
    REPO_URL: https://github.com/ldsj007/LIENOL-Open-2020-10-10
    REPO_BRANCH: 19.07
    UPLOAD_PACKAGES_DIR: false
    UPLOAD_TARGETS_DIR: false
    UPLOAD_FIRMWARE: true
    UPLOAD_TO_ARTIFACTS: false
    UPLOAD_TO_REALEASE: false
    UPLOAD_TO_COWTRANSFER: false
    WECHAT_NOTIFICATION: false
Cloning into 'openwrt'...
fatal: could not read Username for 'https://github.com': No such device or address
Error: Process completed with exit code 128.

**Comment by hyird** [comment]
https://github.com/ldsj007/LIENOL-Open-2020-10-10  你这打得开么。。。。。。

**Comment by hyird** [comment]
自己仓库地址填错了吧

**Comment by ldsj007** [comment]
我感觉就是，但是不确定。哈哈。
