### ISSUE TITLE
hc5962 b70 无线补丁002-fix-mtwifi.patch

### ISSUE THREAD

**Issue by wzslrb** [hyird/Action-Openwrt#3]
002-fix-mtwifi.patch
两个工厂固件都开不了机 今天编译的 升级固件不可用
openwrt-ramips-mt7621-asus_rt-ac65p-squashfs-factory.bin
openwrt-ramips-mt7621-asus_rt-ac85p-squashfs-factory.bin

**Comment by hyird** [comment]
你等等 我把b70拿回来试试

**Comment by hyird** [comment]
你到底什么设备

**Comment by hyird** [comment]
无论是B70 还是  asus_rt-ac65p 都是用的开源 驱动
我打的patch 对其没有任何的改动
