### ISSUE TITLE
可否添加 binfmt 支持, 谢谢.

### ISSUE THREAD

**Issue by radiocom** [hyird/Action-Openwrt#4]
需要用到binfmt, 添加很简单,  CONFIG_BINFMT_MISC=y
参考: https://www.right.com.cn/forum/thread-4052047-1-1.html

理由:
我需要在docker里面跑x86的wine, 用Wine来运行windows版本的迅雷.
而且我发现有些人会需要跑Arm的docker. 相信很多人也会有同样的需求.
谢谢!

**Comment by hyird** [comment]
ok
